<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>hu.bcsabi.petstore</groupId>
        <artifactId>petstore</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>petstore-bom</artifactId>
    <packaging>pom</packaging>

    <name>Pet Store BOM</name>

    <properties>
        <springdoc-openapi.version>3.0.3</springdoc-openapi.version>
        <swagger.version>2.2.47</swagger.version>
        <mapstruct.version>1.6.3</mapstruct.version>
        <lombok-mapstruct-binding.version>0.2.0</lombok-mapstruct-binding.version>
        <parsson.version>1.1.9</parsson.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- Importok -->
            <dependency>
                <groupId>org.springframework.grpc</groupId>
                <artifactId>spring-grpc-dependencies</artifactId>
                <version>${spring-grpc.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-bom</artifactId>
                <version>${springdoc-openapi.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- Projekt függőségek -->
            <dependency>
                <groupId>hu.bcsabi.petstore</groupId>
                <artifactId>petstore-common-core</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>hu.bcsabi.petstore</groupId>
                <artifactId>petstore-common-jpa</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>hu.bcsabi.petstore</groupId>
                <artifactId>petstore-common-web</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>hu.bcsabi.petstore</groupId>
                <artifactId>petstore-common-grpc</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>hu.bcsabi.petstore</groupId>
                <artifactId>petstore-order-api</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>hu.bcsabi.petstore</groupId>
                <artifactId>petstore-order-api-rest</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>hu.bcsabi.petstore</groupId>
                <artifactId>petstore-order-api-grpc</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!-- Egyéb függőségek -->
            <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-annotations-jakarta</artifactId>
                <version>${swagger.version}</version>
            </dependency>

            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>

            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>

            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok-mapstruct-binding</artifactId>
                <version>${lombok-mapstruct-binding.version}</version>
            </dependency>

            <dependency>
                <groupId>org.eclipse.parsson</groupId>
                <artifactId>parsson</artifactId>
                <version>${parsson.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
